version: '3.8'

services:
  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-llm-app
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - redis

  redis:
    image: redis:6-alpine
    container_name: redis-cache
    ports:
      - "6379:6379"